logging:
  level:
    io:
      netty: DEBUG
      reactor: DEBUG
    org.springframework:
      data.r2dbc: INFO
      boot.web: INFO
      cloud: DEBUG
      intergration: DEBUG
    com.kakaopay: INFO
  pattern:
    console: '%logger{30}:%line - %msg%n'
