spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: sunga
    password: sunga
  session:
    store-type: redis
  redis:
    host: localhost
    password:
    port: 6379
  liquibase:
    change-log: classpath:/db/seeding-changelog-master.yaml
  devtools:
    livereload:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///seefing?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sunga
    password: sunga

application:
  keycloak:
    auth-url: http://localhost:9080/auth
    master-realm-id: master
    custom-realm-id: seeding
    admin-user-id: sunga
    admin-user-password: sunga
    client-id: admin-cli
