eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: room-service-input
          group: room-service
          content-type: application/json
  r2dbc:
    url: r2dbc:h2:mem:///seefing?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sunga
    password: sunga
  session:
    store-type: redis
  redis:
    host: localhost
    password:
    port: 6379
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'loggers','threaddump']
