eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: sprinkle-service-input
          group: sprinkle-service
          content-type: application/json
        output:
          destination: sprinkle-service-output
          group: room-service
          content-type: application/json

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'loggers','threaddump']
